import Head from "next/head";

export default function MetaTags({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <Head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
      <title>{title}</title>
      <meta name="description" content={description} />
      <meta property="og:type" content="website" />
    </Head>
  );
}
